### ISSUE TITLE
unexpected install error?

### ISSUE THREAD

**Issue by cboettig** [ropensci/hunspell#9]
Hey @jeroenooms ,

Not sure what I'm doing wrong here, but failing to install `hunspell` on, say, `rocker/hadleyverse` docker image.  I get:

```
install.packages("hunspell")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/hunspell_1.2.tar.gz'
Content type 'application/x-gzip' length 2325111 bytes (2.2 MB)
==================================================
downloaded 2.2 MB

* installing *source* package ‘hunspell’ ...
** package ‘hunspell’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-I/usr/include/hunspell
Using PKG_LIBS=-lhunspell-1.4
** libs
g++ -I/usr/share/R/include -DNDEBUG -I/usr/include/hunspell  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -I/usr/share/R/include -DNDEBUG -I/usr/include/hunspell  -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c check.cpp -o check.o
In file included from check.cpp:1:0:
utils.h: In member function ‘short unsigned int* hunspell_dict::get_wordchars_utf16(int*)’:
utils.h:52:41: error: no matching function for call to ‘Hunspell::get_wordchars_utf16(int*&)’
     return pMS_->get_wordchars_utf16(len);
                                         ^
In file included from utils.h:1:0,
                 from check.cpp:1:
/usr/include/hunspell/hunspell.hxx:220:30: note: candidate: const std::vector<w_char>& Hunspell::get_wordchars_utf16()
   const std::vector<w_char>& get_wordchars_utf16();
                              ^
/usr/include/hunspell/hunspell.hxx:220:30: note:   candidate expects 0 arguments, 1 provided
/usr/lib/R/etc/Makeconf:141: recipe for target 'check.o' failed
make: *** [check.o] Error 1
ERROR: compilation failed for package ‘hunspell’
* removing ‘/usr/local/lib/R/site-library/hunspell’

The downloaded source packages are in
	‘/tmp/RtmpjOKtGF/downloaded_packages’
Warning message:
In install.packages("hunspell") :
  installation of package ‘hunspell’ had non-zero exit status
```

**Comment by jeroenooms** [comment]
Kurt has notified me about this as well. Hunspell has recently gotten a new maintainer who has overhauled the API. So I need to update the binings to work with libhunspell 1.4

**Comment by cboettig** [comment]
ok, cool, thanks

**Comment by jeroenooms** [comment]
This is now finally fixed. Took 10 times more work than I thought :( Switched the package to bundle `libhunspell` because their API keeps breaking so we can't rely on the system version anymore.

**Comment by cboettig** [comment]
great, thanks.  can you just ping me when it hits cran so I can add it back into hadleyverse image (since devtools suggests hunspell)? thanks!

**Comment by jeroenooms** [comment]
OK will do. It has been submitted, waiting for Kurt...

**Comment by jeroenooms** [comment]
This is on CRAN now.

**Comment by tomsjogren** [comment]
Hi, I'm still getting this error.. any updates?

**Comment by jeroenooms** [comment]
@tomsjogren with the latest version? That seems very unlikely, we now bundle hunspell with the package. Can you show us the full output of your install and `sessionInfo()` pls?
